---
development:
  cloud_name: llalhf6gz
  api_key: '944658529318155'
  api_secret: yJFOVlHInSGiafkbMg69MdEuUuc
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: llalhf6gz
  api_key: '944658529318155'
  api_secret: yJFOVlHInSGiafkbMg69MdEuUuc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: llalhf6gz
  api_key: '944658529318155'
  api_secret: yJFOVlHInSGiafkbMg69MdEuUuc
  enhance_image_tag: true
  static_image_support: true
